### ISSUE TITLE
ValueError: illegal value in 4th argument of internal gesdd。I encountered the following error while trying to use adapt_model. py. Is there a solution?

### ISSUE THREAD

**Issue by 2279072142** [tomlimi/DAMA#6]
When I input the following command at the terminal.
`python adapt_model.py --param_number 7 --method "DAMA" --request_file "train_dama.json" --num_layers 11  --post_linear True --mixed_update True --null_dim 128 --no_colinear_vs True --use_neutral True --vs_at_last True  --delta_only True --no_whitening True  --random_seed 45
`

/home/ubuntu/anaconda3/envs/DAMA_BYH/lib/python3.10/site-packages/sklearn/cross_decomposition/_pls.py:99: RuntimeWarning: divide by zero encountered in divide
  y_weights = np.dot(Y.T, x_score) / np.dot(x_score.T, x_score)
/home/ubuntu/anaconda3/envs/DAMA_BYH/lib/python3.10/site-packages/sklearn/cross_decomposition/_pls.py:113: ConvergenceWarning: Maximum number of iterations reached
  warnings.warn("Maximum number of iterations reached", ConvergenceWarning)
/home/ubuntu/anaconda3/envs/DAMA_BYH/lib/python3.10/site-packages/sklearn/cross_decomposition/_pls.py:345: UserWarning: y residual is constant at iteration 19
  warnings.warn(f"y residual is constant at iteration {k}")
Traceback (most recent call last):
  File "/home/ubuntu/BYH/LLM/DAMA-main/src/adapt_model.py", line 232, in <module>
    model_new, orig_weights = model_editing(
  File "/home/ubuntu/BYH/LLM/DAMA-main/src/adapt_model.py", line 83, in model_editing
    model_new, orig_weights = apply_dama_to_model(
  File "/home/ubuntu/BYH/LLM/DAMA-main/src/dama/dama_main.py", line 221, in apply_dama_to_model
    projections = execute_dama(model, tok, requests, hparams, ncv=ncv, val=val, use_neutral=use_neutral,
  File "/home/ubuntu/BYH/LLM/DAMA-main/src/dama/dama_main.py", line 482, in execute_dama
    pls.fit(H_left, H_right)
  File "/home/ubuntu/anaconda3/envs/DAMA_BYH/lib/python3.10/site-packages/sklearn/cross_decomposition/_pls.py", line 713, in fit
    super().fit(X, y)
  File "/home/ubuntu/anaconda3/envs/DAMA_BYH/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/DAMA_BYH/lib/python3.10/site-packages/sklearn/cross_decomposition/_pls.py", line 393, in fit
    pinv2(np.dot(self.x_loadings_.T, self.x_weights_), check_finite=False),
  File "/home/ubuntu/anaconda3/envs/DAMA_BYH/lib/python3.10/site-packages/scipy/linalg/_basic.py", line 1447, in pinv
    u, s, vh = _decomp_svd.svd(a, full_matrices=False, check_finite=False)
  File "/home/ubuntu/anaconda3/envs/DAMA_BYH/lib/python3.10/site-packages/scipy/linalg/_decomp_svd.py", line 166, in svd
    raise ValueError('illegal value in %dth argument of internal gesdd'
ValueError: illegal value in 4th argument of internal gesdd

**My conda env:**
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
accelerate                0.19.0                   pypi_0    pypi
asttokens                 2.4.1              pyhd8ed1ab_0    conda-forge
bzip2                     1.0.8                h5eee18b_6    defaults
ca-certificates           2024.7.4             hbcca054_0    conda-forge
certifi                   2024.7.4                 pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
comm                      0.2.2              pyhd8ed1ab_0    conda-forge
concept-erasure           0.2.4                    pypi_0    pypi
contourpy                 1.2.1                    pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
datasets                  1.2.1                    pypi_0    pypi
debugpy                   1.6.7           py310h6a678d5_0    defaults
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
dill                      0.3.8                    pypi_0    pypi
exceptiongroup            1.2.0              pyhd8ed1ab_2    conda-forge
executing                 2.0.1              pyhd8ed1ab_0    conda-forge
filelock                  3.15.4                   pypi_0    pypi
fonttools                 4.53.1                   pypi_0    pypi
fsspec                    2024.6.1                 pypi_0    pypi
huggingface-hub           0.23.4                   pypi_0    pypi
idna                      3.7                      pypi_0    pypi
importlib-metadata        8.0.0              pyha770c72_0    conda-forge
importlib_metadata        8.0.0                hd8ed1ab_0    conda-forge
ipykernel                 6.29.5             pyh3099207_0    conda-forge
ipython                   8.26.0             pyh707e725_0    conda-forge
jedi                      0.19.1             pyhd8ed1ab_0    conda-forge
jinja2                    3.1.4                    pypi_0    pypi
joblib                    1.4.2                    pypi_0    pypi
jupyter_client            8.6.2              pyhd8ed1ab_0    conda-forge
jupyter_core              5.7.2           py310hff52083_0    conda-forge
kiwisolver                1.4.5                    pypi_0    pypi
langcodes                 3.4.0                    pypi_0    pypi
language-data             1.2.0                    pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1    defaults
libffi                    3.4.4                h6a678d5_1    defaults
libgcc-ng                 14.1.0               h77fa898_0    conda-forge
libgomp                   14.1.0               h77fa898_0    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libstdcxx-ng              11.2.0               h1234567_1    defaults
libuuid                   1.41.5               h5eee18b_0    defaults
lxml                      5.2.2                    pypi_0    pypi
marisa-trie               1.2.0                    pypi_0    pypi
markupsafe                2.1.5                    pypi_0    pypi
matplotlib                3.9.1                    pypi_0    pypi
matplotlib-inline         0.1.7              pyhd8ed1ab_0    conda-forge
mpmath                    1.3.0                    pypi_0    pypi
multiprocess              0.70.16                  pypi_0    pypi
ncurses                   6.4                  h6a678d5_0    defaults
nest-asyncio              1.6.0              pyhd8ed1ab_0    conda-forge
networkx                  3.3                      pypi_0    pypi
numpy                     2.0.0                    pypi_0    pypi
nvidia-cublas-cu12        12.1.3.1                 pypi_0    pypi
nvidia-cuda-cupti-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-nvrtc-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-runtime-cu12  12.1.105                 pypi_0    pypi
nvidia-cudnn-cu12         8.9.2.26                 pypi_0    pypi
nvidia-cufft-cu12         11.0.2.54                pypi_0    pypi
nvidia-curand-cu12        10.3.2.106               pypi_0    pypi
nvidia-cusolver-cu12      11.4.5.107               pypi_0    pypi
nvidia-cusparse-cu12      12.1.0.106               pypi_0    pypi
nvidia-nccl-cu12          2.20.5                   pypi_0    pypi
nvidia-nvjitlink-cu12     12.5.82                  pypi_0    pypi
nvidia-nvtx-cu12          12.1.105                 pypi_0    pypi
openssl                   3.3.1                h4ab18f5_1    conda-forge
packaging                 24.1               pyhd8ed1ab_0    conda-forge
pandas                    2.2.2                    pypi_0    pypi
parso                     0.8.4              pyhd8ed1ab_0    conda-forge
pexpect                   4.9.0              pyhd8ed1ab_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    10.4.0                   pypi_0    pypi
pip                       24.0            py310h06a4308_0    defaults
platformdirs              4.2.2              pyhd8ed1ab_0    conda-forge
portalocker               2.10.0                   pypi_0    pypi
prompt-toolkit            3.0.47             pyha770c72_0    conda-forge
protobuf                  3.20.0                   pypi_0    pypi
psutil                    6.0.0           py310hc51659f_0    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pyarrow                   16.1.0                   pypi_0    pypi
pygments                  2.18.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.1.2                    pypi_0    pypi
python                    3.10.14              h955ad1f_1    defaults
python-dateutil           2.9.0.post0              pypi_0    pypi
python_abi                3.10                    2_cp310    conda-forge
pytz                      2024.1                   pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
pyzmq                     25.1.2          py310h6a678d5_0    defaults
readline                  8.2                  h5eee18b_0    defaults
regex                     2024.5.15                pypi_0    pypi
requests                  2.32.3                   pypi_0    pypi
sacrebleu                 2.4.1                    pypi_0    pypi
safetensors               0.4.3                    pypi_0    pypi
scikit-learn              1.5.1                    pypi_0    pypi
scipy                     1.14.0                   pypi_0    pypi
sentencepiece             0.1.99                   pypi_0    pypi
setuptools                69.5.1          py310h06a4308_0    defaults
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.45.3               h5eee18b_0    defaults
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
sympy                     1.12.1                   pypi_0    pypi
tabulate                  0.9.0                    pypi_0    pypi
threadpoolctl             3.5.0                    pypi_0    pypi
tk                        8.6.14               h39e8969_0    defaults
tokenizers                0.13.3                   pypi_0    pypi
torch                     2.3.1                    pypi_0    pypi
tornado                   6.4.1           py310hc51659f_0    conda-forge
tqdm                      4.49.0                   pypi_0    pypi
traitlets                 5.14.3             pyhd8ed1ab_0    conda-forge
transformers              4.30.2                   pypi_0    pypi
triton                    2.3.1                    pypi_0    pypi
typing_extensions         4.12.2             pyha770c72_0    conda-forge
tzdata                    2024.1                   pypi_0    pypi
urllib3                   2.2.2                    pypi_0    pypi
wcwidth                   0.2.13             pyhd8ed1ab_0    conda-forge
wheel                     0.43.0          py310h06a4308_0    defaults
xxhash                    3.4.1                    pypi_0    pypi
xz                        5.4.6                h5eee18b_1    defaults
zeromq                    4.3.5                h6a678d5_0    defaults
zipp                      3.19.2             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h5eee18b_1    defaults

**Comment by tomlimi** [comment]
Hi,
Thanks for reporting. Please try installing an earlier version of scikit-learn:
`pip install --force-reinstall "scikit-learn==1.2.2"`
Let me know if it helps.

**Comment by 2279072142** [comment]
> Hi, Thanks for reporting. Please try installing an earlier version of scikit-learn and scipy:
> 
> ```
> pip install --force-reinstall "scikit-learn==1.2.2" 
> pip install --force-reinstall "scipy==1.10.1"
> ```
> 
> Let me know if it helps.

Thank you for your reply. I changed the data file to dama_trainjson to avoid this error. But the training process is very long. Can you tell me the approximate training time for each model? thank you

**Comment by tomlimi** [comment]
The error should not be connected to the training data used.
 Could you share which data file did you used previously, which produced the error?
 
 Regarding training time: it depends of multiple factors: model size (I see it is 7 billion parameters in your case) and the processing unit. We used a single A40 GPU, it took ~1.5 hours to compute keys and values for projection and then ~2 hours to compute projections. I hope that helps!
