### ISSUE TITLE
llama_7B does not exist in Hugging Face

### ISSUE THREAD

**Issue by Kowndinya2000** [tomlimi/DAMA#7]
`trace.py` tries to pull `llama_7B` (Model name) from Hugging Face. However that is not available. Please provide the correct model name for me to use `trace.py`. 

`requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/llama_7B/resolve/main/tokenizer_config.json`

Thanks.

**Comment by tomlimi** [comment]
Hi Kowndinya,
Thanks for reporting. The original Llama 1 models were not officially distributed in Huggingface. There are two ways to access them:
1. request access from Meta filling this [form](https://docs.google.com/forms/d/e/1FAIpQLSfqNECQnMkycAp2jP4Z9TFX0cGR4uf7b_fBxjY_OjhJILlKGA/viewform). Then the downloaded model should be saved in `MODEL_DIR` specified in [globals.yml](https://github.com/tomlimi/DAMA/blob/main/src/globals.yml)
OR
2. Use unofficial [huggyllama](https://huggingface.co/huggyllama) release, by providing flag `--model_name_path huggyllama/llama-7b` or a model with different number of parameters.

Please note that this is a solution for Llama 1. Tracing also works for newer [Llama 2](https://huggingface.co/meta-llama/Llama-2-7b-hf) models.
